#pragma once

static const char INDEX_HTML[] =
"<!DOCTYPE html><html lang='en'><head>"
"<meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>KC868-A2v3</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font:14px system-ui,sans-serif;background:#0f172a;color:#e2e8f0;min-height:100vh}"
".header{background:#1e293b;padding:12px 16px;display:flex;align-items:center;justify-content:space-between;border-bottom:2px solid #334155}"
".header h1{font-size:18px;color:#38bdf8}"
".status-dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:6px}"
".status-dot.on{background:#22c55e;box-shadow:0 0 6px #22c55e}"
".status-dot.off{background:#ef4444}"
".tabs{display:flex;background:#1e293b;overflow-x:auto;border-bottom:1px solid #334155}"
".tabs button{flex:1;min-width:80px;padding:10px 8px;border:none;background:none;color:#94a3b8;font-size:12px;cursor:pointer;border-bottom:2px solid transparent;transition:all .2s}"
".tabs button:hover{color:#e2e8f0}"
".tabs button.active{color:#38bdf8;border-bottom-color:#38bdf8}"
".content{padding:12px;max-width:800px;margin:0 auto}"
".tab-content{display:none}"
".tab-content.active{display:block}"
".card{background:#1e293b;border-radius:8px;padding:12px;margin-bottom:12px;border:1px solid #334155}"
".card h2{font-size:14px;color:#38bdf8;margin-bottom:8px;padding-bottom:6px;border-bottom:1px solid #334155}"
".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:8px}"
".stat{text-align:center;padding:8px;background:#0f172a;border-radius:6px}"
".stat .val{font-size:22px;font-weight:bold;color:#38bdf8}"
".stat .lbl{font-size:10px;color:#94a3b8;margin-top:4px}"
".relay-row{display:flex;align-items:center;justify-content:space-between;padding:10px;background:#0f172a;border-radius:6px;margin-bottom:6px}"
".relay-name{font-weight:600}"
".relay-state{font-size:12px;padding:4px 10px;border-radius:4px;font-weight:600}"
".relay-state.on{background:#22c55e;color:#000}"
".relay-state.off{background:#475569;color:#e2e8f0}"
"button{padding:8px 16px;border:none;border-radius:6px;cursor:pointer;font-size:13px;font-weight:600;transition:all .2s}"
".btn-on{background:#22c55e;color:#000}"
".btn-on:hover{background:#16a34a}"
".btn-off{background:#ef4444;color:#fff}"
".btn-off:hover{background:#dc2626}"
".btn-blue{background:#2563eb;color:#fff}"
".btn-blue:hover{background:#1d4ed8}"
".btn-sm{padding:4px 10px;font-size:11px}"
"input,select{width:100%;padding:8px 10px;border:1px solid #334155;border-radius:6px;background:#0f172a;color:#e2e8f0;font-size:13px;margin-bottom:8px}"
"input:focus,select:focus{outline:none;border-color:#38bdf8}"
"label{display:block;font-size:11px;color:#94a3b8;margin-bottom:2px;text-transform:uppercase;letter-spacing:.5px}"
".log-entry{padding:6px 0;border-bottom:1px solid #1e293b;font-size:12px;color:#94a3b8}"
".log-entry .ts{color:#64748b;margin-right:8px}"
".log-entry .evt{color:#38bdf8}"
".auto-row{display:flex;align-items:center;gap:8px;padding:8px;background:#0f172a;border-radius:6px;margin-bottom:6px;flex-wrap:wrap;font-size:12px}"
".auto-row select{width:auto;min-width:100px;margin:0}"
".auto-row input{width:60px;margin:0}"
".switch{position:relative;display:inline-block;width:44px;height:22px}"
".switch input{opacity:0;width:0;height:0}"
".slider{position:absolute;cursor:pointer;top:0;left:0;right:0;bottom:0;background:#475569;border-radius:22px;transition:.3s}"
".slider:before{position:absolute;content:'';height:16px;width:16px;left:3px;bottom:3px;background:#e2e8f0;border-radius:50%;transition:.3s}"
"input:checked+.slider{background:#22c55e}"
"input:checked+.slider:before{transform:translateX(22px)}"
".toast{position:fixed;bottom:16px;right:16px;background:#22c55e;color:#000;padding:10px 20px;border-radius:8px;font-weight:600;font-size:13px;opacity:0;transition:opacity .3s;z-index:999}"
".toast.show{opacity:1}"
".toast.err{background:#ef4444;color:#fff}"
"@media(max-width:480px){.grid{grid-template-columns:repeat(2,1fr)}.header h1{font-size:14px}}"
"</style></head><body>"
"<div class='header'><h1>KC868-A2v3</h1>"
"<div style='display:flex;gap:16px;font-size:12px;align-items:center'>"
"<span id='wifi-status'>WiFi: --</span>"
"<span id='mqtt-status'>MQTT: --</span>"
"<span id='gsm-status'>4G: --</span>"
"</div></div>"
"<div class='tabs'>"
"<button class='active' data-tab='dash'>Dashboard</button>"
"<button data-tab='relays'>Relays</button>"
"<button data-tab='inputs'>Inputs</button>"
"<button data-tab='sensors'>Sensors</button>"
"<button data-tab='wifi'>WiFi</button>"
"<button data-tab='config'>Config</button>"
"<button data-tab='automations'>Automations</button>"
"<button data-tab='log'>Log</button>"
"</div>"
"<div class='content'>"

"<div class='tab-content active' id='tab-dash'>"
"<div class='card'><h2>System Status</h2><div class='grid' id='dash-stats'></div></div>"
"<div class='card'><h2>Relays</h2><div id='dash-relays'></div></div>"
"<div class='card'><h2>Inputs</h2><div id='dash-inputs'></div></div>"
"<div class='card'><h2>Sensors</h2><div id='dash-sensors'></div></div>"
"</div>"

"<div class='tab-content' id='tab-relays'>"
"<div class='card'><h2>Relay Control</h2><div id='relay-controls'></div></div>"
"</div>"

"<div class='tab-content' id='tab-inputs'>"
"<div class='card'><h2>Digital Inputs</h2><div id='input-status'></div></div>"
"</div>"

"<div class='tab-content' id='tab-sensors'>"
"<div class='card'><h2>Temperature Sensors</h2><div id='sensor-readings'></div></div>"
"</div>"

"<div class='tab-content' id='tab-wifi'>"
"<div class='card'><h2>WiFi Connection</h2><div id='wifi-info'></div>"
"<label>SSID</label><input id='wifi-ssid' placeholder='Router SSID'>"
"<label>Password</label><input id='wifi-pass' type='password' placeholder='Password (min 8 chars)'>"
"<div style='display:flex;gap:8px;margin-top:8px'>"
"<button class='btn-blue' onclick='wifiConnect()'>Connect</button>"
"<button class='btn-off btn-sm' onclick='wifiDisconnect()'>Disconnect</button>"
"</div></div>"
"</div>"

"<div class='tab-content' id='tab-config'>"
"<div class='card'><h2>Device Configuration</h2><div id='config-fields'></div>"
"<button class='btn-blue' onclick='saveConfig()' style='margin-top:8px'>Save to Flash</button></div>"
"<div class='card'><h2>Actions</h2>"
"<button class='btn-off' onclick='rebootDevice()'>Reboot Device</button>"
"<button class='btn-off btn-sm' style='margin-left:8px' onclick='allOff()'>Emergency All Off</button>"
"</div></div>"

"<div class='tab-content' id='tab-automations'>"
"<div class='card'><h2>Automation Rules</h2><div id='auto-list'></div>"
"<div class='card' style='background:#0f172a'><h2>Add Rule</h2>"
"<div class='auto-row'>"
"<select id='auto-trigger'><option value='input_1'>Input 1 ON</option><option value='input_2'>Input 2 ON</option><option value='temp1_high'>T1 > threshold</option><option value='temp1_low'>T1 < threshold</option></select>"
"<span>→ Relay</span>"
"<select id='auto-relay'><option value='0'>Relay 1</option><option value='1'>Relay 2</option></select>"
"<select id='auto-action'><option value='on'>ON</option><option value='off'>OFF</option><option value='timed'>Timed</option></select>"
"<input id='auto-duration' placeholder='sec' value='10' style='width:50px'>"
"<button class='btn-blue btn-sm' onclick='addAutomation()'>Add</button>"
"</div></div></div></div>"

"<div class='tab-content' id='tab-log'>"
"<div class='card'><h2>Event Log</h2><div id='log-entries'></div></div>"
"</div>"

"</div><div class='toast' id='toast'></div>"
"<script>"
"let automations=[];let evtLog=[];const MAX_LOG=50;"
"function toast(m,e){const t=document.getElementById('toast');t.textContent=m;t.className='toast'+(e?' err':'')+' show';setTimeout(()=>t.className='toast',2000)}"
"function addLog(evt){evtLog.unshift({ts:new Date().toLocaleTimeString(),evt:evt});if(evtLog.length>MAX_LOG)evtLog.pop();renderLog()}"
"async function api(url,body){try{const opts=body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{};const r=await fetch(url,opts);return r.json()}catch(e){return null}}"

"async function poll(){"
"const s=await api('/api/status');if(s){"
"document.getElementById('dash-stats').innerHTML="
"'<div class=stat><div class=val>'+s.uptime+'s</div><div class=lbl>Uptime</div></div>'"
"+'<div class=stat><div class=val>'+(s.free_heap/1024|0)+'K</div><div class=lbl>Free Heap</div></div>'"
"+'<div class=stat><div class=val>'+s.modem_rssi+'</div><div class=lbl>4G RSSI dBm</div></div>'"
"+'<div class=stat><div class=val>'+s.rtc_temp.toFixed(1)+'&deg;C</div><div class=lbl>RTC Temp</div></div>'"
"+'<div class=stat><div class=val>'+(s.sd_mounted?'OK':'--')+'</div><div class=lbl>SD Card</div></div>'"
"+'<div class=stat><div class=val>'+(s.wifi_connected?'OK':'--')+'</div><div class=lbl>WiFi</div></div>';"
"document.getElementById('wifi-status').innerHTML='<span class=status-dot '+(s.wifi_connected?'on':'off')+'></span>WiFi';"
"document.getElementById('mqtt-status').innerHTML='<span class=status-dot '+(s.mqtt_connected?'on':'off')+'></span>MQTT';"
"document.getElementById('gsm-status').innerHTML='<span class=status-dot '+(s.modem_connected?'on':'off')+'></span>4G '+s.modem_rssi+'dBm';"
"}"
"const r=await api('/api/relays');if(r){"
"let h='';r.forEach((v,i)=>{h+='<div class=relay-row><span class=relay-name>Relay '+(i+1)+'</span><span class=\"relay-state '+(v?'on':'off')+'\">'+(v?'ON':'OFF')+'</span></div>'});"
"document.getElementById('dash-relays').innerHTML=h;"
"let c='';r.forEach((v,i)=>{c+='<div class=relay-row><span class=relay-name>Relay '+(i+1)+'</span><div>';"
"c+='<button class=\"btn-on btn-sm\" onclick=\"relaySet('+i+',1)\">ON</button> ';"
"c+='<button class=\"btn-off btn-sm\" onclick=\"relaySet('+i+',0)\">OFF</button> ';"
"c+='<input type=number id=timed-'+i+' placeholder=sec value=10 style=\"width:50px;display:inline;margin:0\"> ';"
"c+='<button class=\"btn-blue btn-sm\" onclick=\"relayTimed('+i+')\">Timed</button>';"
"c+='<span class=\"relay-state '+(v?'on':'off')+'\" style=margin-left:8px>'+(v?'ON':'OFF')+'</span></div></div>'});"
"document.getElementById('relay-controls').innerHTML=c;"
"}"
"const inp=await api('/api/inputs');if(inp){"
"let h='';inp.forEach((v,i)=>{h+='<div class=relay-row><span class=relay-name>Input '+(i+1)+'</span><span class=\"relay-state '+(v?'on':'off')+'\">'+(v?'ACTIVE':'IDLE')+'</span></div>'});"
"document.getElementById('dash-inputs').innerHTML=h;"
"document.getElementById('input-status').innerHTML=h;"
"}"
"const sn=await api('/api/sensors');if(sn){"
"document.getElementById('dash-sensors').innerHTML="
"'<div class=stat><div class=val>'+(sn.temp_1>-900?sn.temp_1.toFixed(1)+'&deg;C':'--')+'</div><div class=lbl>TMP1 (GPIO18)</div></div>'"
"+'<div class=stat><div class=val>'+(sn.temp_2>-900?sn.temp_2.toFixed(1)+'&deg;C':'--')+'</div><div class=lbl>TMP2 (GPIO8)</div></div>';"
"document.getElementById('sensor-readings').innerHTML="
"'<div class=relay-row><span>TMP1 (GPIO18)</span><span class=relay-state>'+(sn.temp_1>-900?sn.temp_1.toFixed(1)+' &deg;C':'N/A')+'</span></div>'"
"+'<div class=relay-row><span>TMP2 (GPIO8)</span><span class=relay-state>'+(sn.temp_2>-900?sn.temp_2.toFixed(1)+' &deg;C':'N/A')+'</span></div>';"
"}"
"const w=await api('/api/wifi');if(w){"
"document.getElementById('wifi-info').innerHTML='<div class=relay-row><span>Mode</span><span class=relay-state on>'+w.mode+'</span></div><div class=relay-row><span>IP</span><span class=relay-state on>'+w.ip+'</span></div><div class=relay-row><span>SSID</span><span class=relay-state on>'+w.ssid+'</span></div>';"
"}"
"const cfg=await api('/api/config');if(cfg){"
"let f='';const keys={device_name:'Device Name',mqtt_broker:'MQTT Broker URI',sensor_read_interval_sec:'Sensor Interval (s)',mqtt_publish_interval_sec:'MQTT Publish Interval (s)',input_debounce_ms:'Debounce (ms)',input_1_inverted:'Input 1 Inverted',input_2_inverted:'Input 2 Inverted',relay_interlock_enabled:'Interlock',lcd_enabled:'LCD Enabled',sd_log_enabled:'SD Log Enabled'};"
"Object.keys(keys).forEach(k=>{const typ=typeof cfg[k]==='boolean'?'checkbox':'text';f+='<label>'+keys[k]+'</label>';"
"if(typ==='checkbox')f+='<label class=switch style=display:block;margin-bottom:8px><input type=checkbox id=cfg-'+k+' '+(cfg[k]?'checked':'')+'><span class=slider></span></label>';"
"else f+='<input id=cfg-'+k+' value=\"'+(cfg[k]||'')+'\">'});"
"document.getElementById('config-fields').innerHTML=f;"
"}"
"renderAutoList();}"
"function renderAutoList(){let h='';automations.forEach((a,i)=>{h+='<div class=auto-row><span>'+a.desc+'</span><button class=\"btn-off btn-sm\" onclick=\"automations.splice('+i+',1);renderAutoList();addLog(\\'Automation removed\\')\">✕</button></div>'});if(!automations.length)h='<div style=color:#64748b;font-size:12px>No automation rules defined</div>';document.getElementById('auto-list').innerHTML=h}"
"async function relaySet(ch,on){await api('/api/relays',{channel:ch,state:!!on});toast('Relay '+(ch+1)+' '+(on?'ON':'OFF'));addLog('Relay '+(ch+1)+' set '+(on?'ON':'OFF'));poll()}"
"async function relayTimed(ch){const d=parseInt(document.getElementById('timed-'+ch).value)||10;await api('/api/relays',{channel:ch,duration:d});toast('Relay '+(ch+1)+' ON for '+d+'s');addLog('Relay '+(ch+1)+' timed '+d+'s')}"
"async function wifiConnect(){const ssid=document.getElementById('wifi-ssid').value;const pass=document.getElementById('wifi-pass').value;const r=await api('/api/wifi',{ssid:ssid,password:pass});toast(r.message||'WiFi connecting...',!r.ok);addLog('WiFi connect: '+ssid)}"
"async function wifiDisconnect(){await api('/api/wifi',{disconnect:true});toast('WiFi disconnected');addLog('WiFi disconnected')}"
"async function saveConfig(){const cfg={};const keys=['device_name','mqtt_broker','sensor_read_interval_sec','mqtt_publish_interval_sec','input_debounce_ms','input_1_inverted','input_2_inverted','relay_interlock_enabled','lcd_enabled','sd_log_enabled'];keys.forEach(k=>{const el=document.getElementById('cfg-'+k);if(el)cfg[k]=el.type==='checkbox'?el.checked:el.value});const r=await api('/api/config',cfg);toast(r.message||'Saved',!r.ok);addLog('Config saved')}"
"async function rebootDevice(){if(confirm('Reboot device?')){await api('/api/reboot');toast('Rebooting...')}}"
"async function allOff(){await api('/api/relays',{all_off:true});toast('All relays OFF');addLog('Emergency all OFF')}"
"function addAutomation(){const trig=document.getElementById('auto-trigger').value;const relay=parseInt(document.getElementById('auto-relay').value);const action=document.getElementById('auto-action').value;const dur=parseInt(document.getElementById('auto-duration').value)||10;const desc=[trig.replace('_',' ').toUpperCase(),'->','Relay '+(relay+1),action==='timed'?'ON '+dur+'s':action.toUpperCase()].join(' ');automations.push({trigger:trig,relay:relay,action:action,duration:dur,desc:desc});renderAutoList();toast('Automation added');addLog('Automation: '+desc)}"
"function renderLog(){document.getElementById('log-entries').innerHTML=evtLog.map(e=>'<div class=log-entry><span class=ts>'+e.ts+'</span><span class=evt>'+e.evt+'</span></div>').join('')}"
"document.querySelectorAll('.tabs button').forEach(b=>{b.onclick=()=>{document.querySelectorAll('.tabs button,.tab-content').forEach(e=>e.classList.remove('active'));b.classList.add('active');document.getElementById('tab-'+b.dataset.tab).classList.add('active')}});"
"addLog('Web UI loaded');poll();setInterval(poll,3000);"
"</script></body></html>";
